apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-proyecto-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/felaponte/proyecto_mlops'
    targetRevision: main
    path: ./komposefiles
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


