apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-hostPath.yaml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-hostPath.yaml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: api-service
    spec:
      containers:
        - args:
            - uv
            - run
            - uvicorn
            - api:app
            - --host
            - 0.0.0.0
            - --port
            - "8989"
          image: s4g0/api-service
          name: api-service
          ports:
            - containerPort: 8989
          resources: {}
      restartPolicy: Always
status: {}
