apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pvc.yaml -o komposefiles/ --volumes persistentVolumeClaim
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-metadata-mlflow
  name: db-metadata-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-metadata-mlflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-pvc.yaml -o komposefiles/ --volumes persistentVolumeClaim
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db-metadata-mlflow
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: mysql:latest
          name: db-metadata-mlflow
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-db
      restartPolicy: Always
      volumes:
        - name: mysql-db
          persistentVolumeClaim:
            claimName: mysql-db
status: {}
