apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-pvc.yaml -o komposefiles/ --volumes persistentVolumeClaim
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-raw-data
  name: db-raw-data
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    io.kompose.service: db-raw-data
status:
  loadBalancer: {}
