apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-ds
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-loader
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-api
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-ds
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-loader
          configMap:
            name: grafana-dashboards-config
        - name: grafana-dashboard-api
          configMap:
            name: grafana-dashboard-api
