apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-service-deployment.yaml
  - api-service-service.yaml
  - db-clean-data-deployment.yaml
  - db-clean-data-service.yaml
  - db-metadata-mlflow-deployment.yaml
  - db-metadata-mlflow-service.yaml
  - db-raw-data-deployment.yaml
  - db-raw-data-service.yaml
  - grafana-dashboard-api.yaml
  - grafana-dashboards-config.yaml
  - grafana-datasources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - locust-deployment.yaml
  - locust-service.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - mlflow-service-deployment.yaml
  - mlflow-service-service.yaml
  - ml-service-deployment.yaml
  - ml-service-service.yaml
  - mysql-db-persistentvolumeclaim.yaml
  - my-db-clean-persistentvolumeclaim.yaml
  - my-db-raw-persistentvolumeclaim.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - streamlit-app-deployment.yaml
  - streamlit-app-service.yaml

images:
  - name: s4g0/mlflow-service
    newTag: v1
  - name: s4g0/api-service
    newTag: v1
  - name: s4g0/streamlit
    newTag: v1