apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-hostPath.yaml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: locust
  name: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: locust
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-hostPath.yaml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: locust
    spec:
      containers:
        - env:
            - name: LOCUST_HOST
              value: http://api-service:8989
          image: s4g0/proyecto_kubernetes:locust
          name: locust
          ports:
            - containerPort: 8089
          resources: {}
      restartPolicy: Always
status: {}
