apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-hostPath.yaml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ml-service
  name: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ml-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-hostPath.yaml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ml-service
    spec:
      containers:
        - args:
            - uv
            - run
            - jupyter
            - lab
            - --ip=0.0.0.0
            - --port=8888
            - --allow-root
          image: s4g0/proyecto_kubernetes:ml_service_1
          name: ml-service
          ports:
            - containerPort: 8888
          resources: {}
          volumeMounts:
            - mountPath: /ml_project/files
              name: ml-service-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/estudiante/9-kubernetes/jupyter-nb/files
          name: ml-service-hostpath0
status: {}
